### PR TITLE
CCM::Format class to convert CCM instances in formatted text

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
Preparation for https://github.com/quattor/ncm-query/issues/6 and for https://github.com/quattor/CCM/issues/43

**Comment by ned21** [comment]
I am afraid I don't really follow what this is for. Could commit ce7d814 provide some more detail as to why this is being added to the library? And then the POD for the library should say a bit more about how and when this it should be used.

**Comment by stdweird** [comment]
@ned21 2 issues i'm trying to resolve: https://github.com/quattor/CCM/issues/43 and https://github.com/quattor/ncm-query/issues/6
They both require to convert an `Element` instance (e.g. '/') to some well defined format (e.g. `json`). 
So i made a new class to do just that.
But `CCM::TextRender` has become very powerful in the meanwhile, and if i was sure i could do all with `CCM::TextRender`, there is no need for a separate class anymore (at least for now the `FORMATS_OTHER` would be empty, and is a bit ugly).
The xml handling is the only thing that might be missing, and might require actual perl code; but it could be done i think (if it is to create pan xml profile format from an element instance, it's not that hard).

Usage is simple and similar to TextRender:
```perl
use EDG::WP4::CCM::Format;
my $el = $cfg->getElement("/");
$fmt = EDG::WP4::CCM::Format->new('json', $el);
print $fmt;
```
(but no `->filewriter` support like `TextRender`).
But i'll update the pod.

**Comment by stdweird** [comment]
@ned21 i managed to generate the panc xml output with TT, so no need for a separate module. i'll remove the `Format.pm` later; maybe i'll also make a new PR.

**Comment by stdweird** [comment]
there will be no separate module, everything will come from `CCM::TextRender`

**Comment by stdweird** [comment]
replaced by #60

**Pull request closed without merging**
