### PR TITLE
change default DB format to CDB_File

### LINKED ISSUE #100: Move default format to CDB_file
Need to figure out if there is any reason not use CDB as default DB format (and if not, switch to it).

Related to https://github.com/quattor/aii/issues/175

Also requires change in default ccm.cfg in maven-tools

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #100

### CODE REVIEW

**Comment by jrha** [comment]
LGTM, can you fix the conflict please?

**Comment by stdweird** [comment]
@jrha done

**Comment by jrha** [comment]
Thanks, I'll leave it open for a bit.

**Comment by ttyS4** [comment]
In general it looks good to me as well.
I would just put the no-code change into a separate commit, but that is just me ;-)

**Pull request merged**
