### PR TITLE
Fetch: refactor in submodules

### PR DESCRIPTION
**Pull request by stdweird**
Besides minor cleanup, no code functionality has been changed. In particular, no modifications to the unittests besides trivial ones were made.

### CODE REVIEW

**Comment by stdweird** [comment]
This is work in prepartion of https://github.com/quattor/CCM/issues/54 and https://github.com/quattor/CAF/issues/62
@ned21 @jrha Should be merged as soon as 15.8 is out. Smallest modification to Fecth makes this unmergable

**Comment by stdweird** [comment]
@ned21 maybe open an issue for it, and i'll do it the whole of CCM (and CAF too :smile: )

**Comment by stdweird** [comment]
@ned21 @jrha anything left to do?

**Comment by jrha** [comment]
Nope, all good.

**Pull request merged**
