### PR TITLE
Add CCM specific tabcompletion support

### LINKED ISSUE #43: Tab completion lookup file
As discussed at the Grenoble workshop, ccm should write out a list of all the paths in a profile when a new profile is fetched, this file should be stored in the same directory as the db file and used by `ncm-query` to support tab completion.
It could be a list of paths, one per line including all sub paths up to the leaf values.

Something like this would be good:
```
/hardware/
/hardware/cards/
/hardware/cards/nic/
/hardware/cards/nic/eth0/
/hardware/cards/nic/eth0/boot
/hardware/cards/nic/eth0/hwaddr
/hardware/cards/nic/eth0/media
/hardware/cards/nic/eth0/name
/hardware/cards/nic/eth0/pxe
```

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #43

### CODE REVIEW

**Comment by stdweird** [comment]
Default does nto do anythign at all. Also other PRs will be needed to add support to actual enduser code.

**Comment by jrha** [comment]
Nice.

**Comment by jrha** [comment]
LGTM, would be good to know that someone from MS has had a pass over this... @ned21?

**Comment by ned21** [comment]
The Perl looks fine but I don't speak bash!

**Comment by stdweird** [comment]
retest this please

**Pull request merged**
