### PR TITLE
CCM::Configuration: remove reference to placeholder

### PR DESCRIPTION
**Pull request by jrha**
Last part of #169, was overlooked in #187.
Blocking for 18.6.

### CODE REVIEW

**Comment by jrha** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2018-07-09T11:58:30+02:00
[INFO] Final Memory: 24M/299M
[INFO] ------------------------------------------------------------------------
```

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
retest this please

**Pull request merged**
