### PR TITLE
Fetch: fetchProfile pod: replace -1 with used $ERROR

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by ned21** [comment]
Quickly scanning the code, I don't understand how undef ever gets returned?

**Comment by stdweird** [comment]
@ned21 in case of https://github.com/stdweird/CCM/blob/e8b8f511cfabcfe9d2d82e31079b9aff90440f74/src/main/perl/Fetch.pm#L181, `$ret` is not set to anything, and then returned at the end. it's also tested https://github.com/quattor/CCM/blob/master/src/test/perl/fetch.t#L535

**Comment by ned21** [comment]
@stdweird that's hideous. :( How difficult is it to change? All calls to fetchProfile must already check for ```undef || $ERROR``` so could we make it always return $ERROR or SUCCESS?

**Comment by stdweird** [comment]
@ned21 would you rather have it immediatley call `return` in that block?
i'd rather let it return `undef` or `0` (with `0` instead of `-1` or `$ERROR`; i 'm not sure we can change `ERROR` to `0`). that way a failure returns something false, like almost all the other code we have, and we can still make a distinction between `download` failure or something worse.

**Comment by ned21** [comment]
@stdweird It should set $res to some value, like the other clauses of the if/elsif/else block and then return via "return $res" at the end.

I agree with signalling different errors with different return codes, which means we cannot rely on boolean (or even tri-state: undef/0/1).  In that case using more negative values would be logical if this was new code. (e.g. $DOWNLOADFAILURE = -2)

If we don't want to collapse all errors down to a single 'false' value then I'm not sure there's much to gain from trying to retain true/false semantics because making this look like other code means the unwary might try to check only true/false, see that it mostly works and then get a true result that also means error. Having said that, 0 would ensure any existing code that treated it as a boolean continued to work. Error could then also be tested in one operation as ```$ret < 1```.

**Comment by stdweird** [comment]
@ned21 first of all , this PR brings the POD in line with the code, nothing more, but also nothing less (it's always nice that the pod is useful enough that you do not have to read the code, esp if the code is ugly :smile: )

if you want this modified, please open a new issue. or i close this PR and make the change part of #122.
if you want a general discussion on return values in quattor, definitely open a new issue :grin:

wrt to changing the return values: i do not agree with different error codes. errors should be undef (or false at least), and code should either report an error or set the failure reason e.g. via the fail attribute (or maybe `die`). although it may be nice to have different return codes, nobody uses them or knows what they mean. e.g. in the case of `fetchProfile` it is only used in `ccm-fetch` script and `aii::Shellfe`. i find very little added value in repeated error message that a "network error" occured; if it failed, to figure out why, you'll look at any previous reported errors/warnings. i actually have to read the code to figure out what is considered as a "network error" (it's a HTTP download failure, and guess what, it might not be related to the network in some cases, like wrong permission on x509 key).

**Pull request merged**
