### PR TITLE
CLI: new query formats, default action and non-options args as paths 

### PR DESCRIPTION
**Pull request by stdweird**
Requires https://github.com/quattor/CAF/pull/126

### CODE REVIEW

**Comment by stdweird** [comment]
This PR provides default action=show format=query and non-option argument profpath, with tabcompletion sourced.
Example output
 * the first 2 are tabcompletion results
 * 3rd is actual run of `ccm`
 * the query format is not the same as ncmquery (`--format=ncmquery` resembles `ncm-query` output)
```
[root@node2201 ~]# ccm /s
/software/  /system/    
[root@node2201 ~]# ccm /system/
/system/aii/           /system/cluster/       /system/kernel/        /system/network/       /system/quattorid      /system/siterelease
/system/blockdevices/  /system/filesystems/   /system/monitoring/    /system/opennebula/    /system/rootmail       /system/state
[root@node2201 ~]# ccm /system/
+-/system
  +-aii
    +-dhcp
...
```

**Comment by stdweird** [comment]
i added a script to be added/linked to `/etc/profile.d` to load the bashcompletion in case you don't want to modify `.bashrc` etc 
```pan
"/software/components/symlink/links" = append(dict(
    "name", "/etc/profile.d/quattor-ccm.sh",
    "target", "/usr/share/quattor/quattor-ccm-profile",
    "replace", dict("all", "yes"),
    ));
```

**Comment by ned21** [comment]
Is /etc/bash_completion.d a Debian-ism or would that be a better choice than /etc/profile.d? What's the rationale behind the minuid=9999? (Apologies if this is some standard/convention that's passed me by!)

**Comment by stdweird** [comment]
@ned21 `/etc/bash_completion.d` is default location for bashcompletion scripts, i.e. also in el6/7 and fedora. however, none of the scripts are sourced by default. for that, you need an extra rpm `bash-completion` on redhat/fedora, and that one will load all bashcompletions (also via some mechanism in `/etc/profile.d`).
the example i added was in case people only want the ccm completion.
the `minuid` is soemthing we use internally for some other profile scripts, not a standard at all (it can be removed, the main issues to handle are restriction to interactive shell and preveting reload).

**Comment by stdweird** [comment]
@ned21 ping?

**Comment by ned21** [comment]
Given that ccm now supports running as non-root, I would imagine this would be useful for every human user and the minuid stuff should be dropped?

As for bash-completion.d v our own profile.d: my gut feeling is that we should install in the standard location and then let the admin decide whether that's activated globally, and users can also source from their .bashrc. If we add it ourselves to profile.d then it's hard for someone to disable.

**Comment by stdweird** [comment]
@ned21 the symlink from `/usr/share/quattor/etc/quattor-ccm-profile` to profile.d is not created, i simply added some example pan code how one can do so if they only want to  add the bashcompletion and have it available for e.g. admin accounts. i can remove the minuid stuff, or i can make it more clear it's just an example?
to clear: the actual tabcompletion code is put in the default location, and it's not enabled in any way, it up to local admin to do so.

**Comment by ned21** [comment]
OK, sorry that makes sense when I re-read 7490ac7. I would normally expect to find an example script in /usr/share/doc or similar, but I see how it makes sense when using quattor to make it symlinkable. So perhaps the script just needs a bit more inline documentation about how it is intended to be used? Otherwise people find a random script on their system and there's no way for them to find out how to use it without reading this PR.

**Comment by stdweird** [comment]
@ned21 i added some comments to the `quattor-ccm-profile` script. i hope it is more clear now.

**Comment by ned21** [comment]
I spotted a typo in the comments but other than LTGM

**Comment by stdweird** [comment]
@ned21 typo fixed

**Comment by ned21** [comment]
I find it very ironic that my message complaining about a typo also contained a typo... This can be merged if the checks pass.

**Comment by jrha** [comment]
test this please

**Pull request merged**
