### PR TITLE
ccm-purge: close db with close_db

### LINKED ISSUE #191: ccm-purge does not work in 18.6
Running ccm-purge gives an error and old files are not removed:

> untie attempted while 1 inner references still exist at /usr/sbin/ccm-purge line 287.

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #191

### CODE REVIEW

**Comment by stdweird** [comment]
@nowack73 this should fix the issue. you can apply the patch use rpm from jenkins https://jenkins0.ugent.be/job/CCM-pr-builder/346/org.quattor.client.libraries$ccm/artifact/org.quattor.client.libraries/ccm/18.6.1-SNAPSHOT/ccm-18.6.1-SNAPSHOT.rpm

@jrha i'll leave this up to you to make a 18.6.1 for this issue or not

**Comment by nowack73** [comment]
@stdweird the fix works fine. Thanks.

**Comment by ned21** [comment]
Do we know why this broke? The commit log is a bit "what" instead of "how/why".

**Comment by jrha** [comment]
@stdweird I'm not sure it warrants a 18.6.1
@ned21 seconded — the commit message explains nothing

**Comment by stdweird** [comment]
@ned21 @jrha better?

**Comment by ned21** [comment]
@stdweird - thanks, makes more sense. Any chance of a replacing #183 with 8b5cb3889 on the basis that a git repo may outlive GitHub's issue tracking?

**Comment by stdweird** [comment]
@ned21 done

**Comment by jrha** [comment]
Much clearer thanks!

**Pull request merged**
